volumes:
  app-logs:
    driver: local

services:
  backend-discovery-server:
    container_name: healthcare-discovery-server
    image: arivanamin/healthcare-backend-discovery-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/

  backend-api-gateway:
    container_name: healthcare-api-gateway
    image: arivanamin/healthcare-backend-api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  tempo:
    container_name: healthcare-tempo
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin

  loki:
    container_name: healthcare-loki
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  promtail:
    container_name: healthcare-promtail
    image: grafana/promtail:2.7.1
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - app-logs:/logs
      - ${HOME}/Apps/Healthcare/Logs:/local-logs
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    container_name: healthcare-prometheus
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    container_name: healthcare-grafana
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  # Services
  backend-appointment-service:
    container_name: healthcare-backend-appointment
    image: arivanamin/healthcare-backend-appointment
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server
      - backend-api-gateway

  backend-billing-service:
    container_name: healthcare-backend-billing
    image: arivanamin/healthcare-backend-billing
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-doctor-service:
    container_name: healthcare-backend-doctor
    image: arivanamin/healthcare-backend-doctor
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-inventory-service:
    container_name: healthcare-backend-inventory
    image: arivanamin/healthcare-backend-inventory
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-lab-service:
    container_name: healthcare-backend-lab
    image: arivanamin/healthcare-backend-lab
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-medical-record-service:
    container_name: healthcare-backend-medical-record
    image: arivanamin/healthcare-backend-medical-record
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-notification-service:
    container_name: healthcare-backend-notification
    image: arivanamin/healthcare-backend-notification
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-patient-service:
    container_name: healthcare-backend-patient
    image: arivanamin/healthcare-backend-patient
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-pharmacy-service:
    container_name: healthcare-backend-pharmacy
    image: arivanamin/healthcare-backend-pharmacy
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-prescription-service:
    container_name: healthcare-backend-prescription
    image: arivanamin/healthcare-backend-prescription
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-radiology-service:
    container_name: healthcare-backend-radiology
    image: arivanamin/healthcare-backend-radiology
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-reporting-service:
    container_name: healthcare-backend-reporting
    image: arivanamin/healthcare-backend-reporting
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-security-service:
    container_name: healthcare-backend-security
    image: arivanamin/healthcare-backend-security
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-staff-service:
    container_name: healthcare-backend-staff
    image: arivanamin/healthcare-backend-staff
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server

  backend-surgery-service:
    container_name: healthcare-backend-surgery
    image: arivanamin/healthcare-backend-surgery
    env_file:
      - .env
    volumes:
      - app-logs:/root/Apps/Healthcare/Logs/
    depends_on:
      - backend-discovery-server
