spring.application.name = discovery-server
server.port = ${EUREKA_PORT:8761}

# ===================================
# BANNER PROPERTIES
# ===================================
project-name = @project.parent.artifactId@
service-name = @project.artifactId@
service-version = @project.version@

# ===================================
# EUREKA
# ===================================
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false
eureka.instance.lease-renewal-interval-in-seconds = 1

lms.eureka.credentials.username = ${EUREKA_USERNAME}
lms.eureka.credentials.password = ${EUREKA_PASSWORD}

# ===================================
# AUDIT EVENT SENSITIVE FIELDS
# ===================================
audit.masking.sensitive.fields[0] = password
audit.masking.sensitive.fields[1] = pin
audit.masking.sensitive.fields[2] = cvv
audit.masking.sensitive.fields[3] = cardNumber
audit.masking.sensitive.fields[4] = ssn
audit.masking.sensitive.fields[5] = secretKey
audit.masking.sensitive.fields[6] = token
