global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'appointment-services'
    metrics_path: '/appointments/actuator/prometheus'
    static_configs:
      - targets: [ '${DOCKER_HOST_IP:-host.docker.internal}:8080' ]
        labels:
          instance: 'Appointment-Service'

  - job_name: 'billing-services'
    metrics_path: '/billings/actuator/prometheus'
    static_configs:
      - targets: [ '${DOCKER_HOST_IP:-host.docker.internal}:8080' ]
        labels:
          instance: 'Billing-Service'
