global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:17001','172.17.0.1:17002' ]
